services:
  app:
    build:
      context: ./chros
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      #NOTE: 本番環境の時は、以下の変数を変えること。
      - NODE_ENV=development

  app-websock:
    build:
      context: ./chros-websock
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      #NOTE: 本番環境の時は、以下の変数を変えること。
      - NODE_ENV=development

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"

  score:
    build:
      context: ./chros-score
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
